server:
  address: wxorder.com
  port: 9527
  servlet:
    context-path: /wxorder
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wxorder?AutoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 9o0p-[=]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: D:\JavaProjects\WXOrderDemo\logs
#  file: D:\JavaProjects\WXOrderDemo\logs\wxod.log
#  level:
##    com.mongode: debug
#    com.mongode.LoggerTest: debug
